PrintMotd no
PrintLastLog no
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM no
PubkeyAuthentication yes
AuthorizedKeysFile /var/lib/gitbox/ssh/authorized_keys
